workflows:
  expo-react-native-android:
    name: Expo React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20.11.0
      vars:
        PACKAGE_NAME: "com.ankitgupta8.tutorfinder"
        EXPO_USERNAME: $EXPO_USERNAME
        EXPO_PASSWORD: $EXPO_PASSWORD
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4096m"
      xcode: latest
      java: 17
    scripts:
      - name: Pre-build cleanup
        script: |
          rm -rf node_modules
          rm -rf android/build
          rm -rf android/app/build
          rm -f package-lock.json
          rm -f yarn.lock
          rm -rf $HOME/.gradle/caches/
      
      - name: Set up local properties
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Fix package.json dependencies
        script: |
          # Create a clean package.json without the undefined dependency
          # Use jq to remove @types/react-native from dependencies if present
          if [ -f package.json ]; then
            jq 'del(.dependencies["@types/react-native"])' package.json > package.json.tmp
            mv package.json.tmp package.json
          fi
      
      - name: Install dependencies
        script: |
          yarn cache clean
          yarn install --network-timeout 300000
          
          # Install specific versions needed
          yarn add expo@~52.0.0 --legacy-peer-deps
          yarn add react-native@0.73.4 --legacy-peer-deps
          yarn add @react-native-async-storage/async-storage --legacy-peer-deps
          yarn add expo-system-ui --legacy-peer-deps
          
          # Add correct development dependencies
          yarn add --dev metro@^0.81.0 metro-config@^0.81.0 metro-resolver@^0.81.0
          yarn add --dev @expo/config-plugins@~9.0.0 @expo/prebuild-config@~8.0.0
          
          # Add @types/react-native as a dev dependency only
          yarn add --dev @types/react-native
      
      - name: Install global tools
        script: |
          npm install -g expo-cli@latest
          npm install -g eas-cli@latest
          
      - name: Configure Expo project
        script: |
          # Create babel.config.js
          cat > babel.config.js << 'EOL'
          module.exports = function(api) {
            api.cache(true);
            return {
              presets: ['babel-preset-expo'],
              plugins: ['@babel/plugin-proposal-export-namespace-from']
            };
          };
          EOL
          
          # Create metro.config.js
          cat > metro.config.js << 'EOL'
          const { getDefaultConfig } = require('expo/metro-config');

          const config = getDefaultConfig(__dirname);

          config.resolver.sourceExts = [
            ...config.resolver.sourceExts,
            'cjs',
            'mjs'
          ];

          module.exports = config;
          EOL
          
          # Create or update app.json
          cat > app.json << 'EOL'
          {
            "expo": {
              "name": "TutorFinder",
              "slug": "tutorfinder",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "userInterfaceStyle": "light",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "assetBundlePatterns": [
                "**/*"
              ],
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.ankitgupta8.tutorfinder"
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#ffffff"
                },
                "package": "com.ankitgupta8.tutorfinder"
              },
              "web": {
                "favicon": "./assets/favicon.png"
              },
              "doctor": {
                "reactNativeDirectoryCheck": {
                  "exclude": ["cloudinary-react-native", "react-native-keyboard-aware-scroll-view"],
                  "listUnknownPackages": false
                }
              }
            }
          }
          EOL
          
          # Create eas.json
          cat > eas.json << 'EOL'
          {
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal"
              },
              "preview": {
                "distribution": "internal"
              },
              "production": {
                "distribution": "store"
              }
            }
          }
          EOL
          
          # Create directories that might be needed
          mkdir -p assets
          
          # Create placeholder icon files if they don't exist
          if [ ! -f "./assets/icon.png" ]; then
            echo "Creating placeholder icon.png"
            convert -size 1024x1024 xc:white ./assets/icon.png || echo "Warning: could not create icon.png"
          fi
          
          if [ ! -f "./assets/splash.png" ]; then
            echo "Creating placeholder splash.png"
            convert -size 1242x2436 xc:white ./assets/splash.png || echo "Warning: could not create splash.png"
          fi
          
          if [ ! -f "./assets/adaptive-icon.png" ]; then
            echo "Creating placeholder adaptive-icon.png"
            convert -size 1024x1024 xc:white ./assets/adaptive-icon.png || echo "Warning: could not create adaptive-icon.png"
          fi
          
      - name: Run Expo Doctor
        script: |
          npx expo-doctor || echo "Continuing despite expo-doctor issues"
      
      - name: Prebuild Android
        script: |
          export EAS_NO_VCS=1
          # Force yes to any prompts during prebuild
          yes | npx expo prebuild --platform android --clean || echo "Prebuild completed with warnings"
          
      - name: Setup keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/keystore.jks
            
            # Create keystore.properties file
            cat > $CM_BUILD_DIR/android/keystore.properties << EOL
            storeFile=keystore.jks
            storePassword=$CM_KEYSTORE_PASSWORD
            keyAlias=$CM_KEY_ALIAS
            keyPassword=$CM_KEY_PASSWORD
            EOL
          else
            echo "No keystore provided. App will be built with debug signing."
          fi
      
      - name: Configure Gradle
        script: |
          cd android
          
          # Update gradle.properties
          cat > gradle.properties << 'EOL'
          org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m
          org.gradle.daemon=true
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.code.style=official
          android.disableAutomaticComponentCreation=true
          EOL
          
          # Fix build.gradle versions
          cat > build.gradle << 'EOL'
          // Top-level build file where you can add configuration options common to all sub-projects/modules.
          
          buildscript {
              ext {
                  buildToolsVersion = "33.0.0"
                  minSdkVersion = 21
                  compileSdkVersion = 33
                  targetSdkVersion = 33
                  kotlinVersion = "1.8.0"
                  ndkVersion = "25.1.8937393"
              }
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath("com.android.tools.build:gradle:7.4.2")
                  classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
                  classpath("de.undercouch:gradle-download-task:5.0.1")
              }
          }
          
          allprojects {
              repositories {
                  maven {
                      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                      url("$rootDir/../node_modules/react-native/android")
                  }
                  maven {
                      // Android JSC is installed from npm
                      url("$rootDir/../node_modules/jsc-android/dist")
                  }
                  mavenCentral {
                      // We don't want to fetch react-native from Maven Central as there are
                      // older versions over there.
                      content {
                          excludeGroup "com.facebook.react"
                      }
                  }
                  google()
                  maven { url 'https://www.jitpack.io' }
              }
          }
          EOL
          
          # Set correct gradle wrapper version
          mkdir -p gradle/wrapper
          cat > gradle/wrapper/gradle-wrapper.properties << 'EOL'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOL
          
      - name: Configure app build.gradle
        script: |
          if [ -f "$CM_BUILD_DIR/android/app/build.gradle" ]; then
            # Add packaging options to app build.gradle
            cat > /tmp/app-build-additions.gradle << 'EOL'
            
            android {
                packagingOptions {
                    pickFirst '**/*.so'
                    exclude 'META-INF/DEPENDENCIES'
                    exclude 'META-INF/LICENSE'
                    exclude 'META-INF/LICENSE.txt'
                    exclude 'META-INF/license.txt'
                    exclude 'META-INF/NOTICE'
                    exclude 'META-INF/NOTICE.txt'
                    exclude 'META-INF/notice.txt'
                    exclude 'META-INF/ASL2.0'
                    exclude 'META-INF/*.kotlin_module'
                }
                
                configurations.all {
                    resolutionStrategy {
                        force 'androidx.core:core-ktx:1.9.0'
                        force 'androidx.appcompat:appcompat:1.6.1'
                    }
                }
            }
            EOL
            
            # Append the content to build.gradle
            cat /tmp/app-build-additions.gradle >> $CM_BUILD_DIR/android/app/build.gradle
            
            # Add keystore configuration if available
            if [ -n "$CM_KEYSTORE" ]; then
              cat > /tmp/signing-config.gradle << EOL
              
              android {
                  signingConfigs {
                      release {
                          if (project.rootProject.file("keystore.properties").exists()) {
                              def keystoreProperties = new Properties()
                              keystoreProperties.load(new FileInputStream(project.rootProject.file("keystore.properties")))
                              storeFile file(keystoreProperties['storeFile'])
                              storePassword keystoreProperties['storePassword']
                              keyAlias keystoreProperties['keyAlias']
                              keyPassword keystoreProperties['keyPassword']
                          }
                      }
                  }
                  buildTypes {
                      release {
                          signingConfig signingConfigs.release
                      }
                  }
              }
              EOL
              
              # Append signing config
              cat /tmp/signing-config.gradle >> $CM_BUILD_DIR/android/app/build.gradle
            fi
          else
            echo "Warning: android/app/build.gradle not found"
          fi
          
      - name: Build Android Release
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean
          
          # Run with debug info but continue even if it fails
          ./gradlew assembleRelease --info --stacktrace > ../gradle_build.log 2>&1 || {
            echo "Gradle build failed, checking logs..."
            cat ../gradle_build.log | grep -A 20 "FAILURE:" || echo "No specific failure message found"
            cat ../gradle_build.log | grep -B 5 -A 15 "error:" || echo "No specific error messages found"
            exit 1
          }
          
      - name: Verify APK
        script: |
          ls -la $CM_BUILD_DIR/android/app/build/outputs/apk/release/ || echo "No APK found in expected location"
          if [ -f "$CM_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk" ]; then
            echo "✅ APK generation completed successfully!"
          else
            echo "❌ APK generation failed - no APK found"
            exit 1
          fi

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/mapping/release/mapping.txt
      - gradle_build.log

    publishing:
      email:
        recipients:
          - ankit.kapilvastu@gmail.com
        notify:
          success: true
          failure: true
