workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.guptaankit9.ankitproject"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install expo-cli@6.3.0
          npm install
      - name: Install sharp-cli globally
        script: |
          npm install -g sharp-cli
      - name: Install compatible expo-system-ui version
        script: |
          npm install expo-system-ui@3.0.0
      - name: Clear Metro Bundler Cache
        script: |
          npx react-native-community/cli start --reset-cache --no-interactive || true
          # Alternative approach
          rm -rf $HOME/.npm/_cacache
          rm -rf $TMPDIR/metro-*
          rm -rf $TMPDIR/haste-map-*
      - name: Validate Metro Configuration
        script: |
          if [ ! -f metro.config.js ]; then
            echo "module.exports = require('@expo/metro-config').getDefaultConfig(__dirname);" > metro.config.js
          fi
      - name: Validate Expo project setup
        script: |
          npx expo doctor || true
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Fix Gradle configuration issues
        script: |
          # Fix compileSdkVersion issue
          MAIN_GRADLE_FILE="$CM_BUILD_DIR/android/build.gradle"
          APP_GRADLE_FILE="$CM_BUILD_DIR/android/app/build.gradle"
          
          # Ensure compileSdkVersion is set in app/build.gradle
          if ! grep -q "compileSdkVersion" "$APP_GRADLE_FILE"; then
            sed -i '' '/apply plugin: "com.android.application"/a\\
            android {\
                compileSdkVersion 34\
            }' "$APP_GRADLE_FILE"
          fi
          
          # Add missing maven repositories
          sed -i '' '/allprojects {/,/}/s/repositories {/repositories {\
                maven {\
                    url "$rootDir\/../node_modules/expo/android/maven"\
                }\
                maven {\
                    url "$rootDir\/../node_modules/react-native/android"\
                }/' "$MAIN_GRADLE_FILE"
          
          # Update Gradle version if needed
          sed -i '' 's/gradle:7\.[0-9]\.[0-9]/gradle:7.5.1/g' "$MAIN_GRADLE_FILE"
          
          # Fix the Android Gradle Plugin version if needed
          sed -i '' 's/com.android.tools.build:gradle:[0-9]\.[0-9]\.[0-9]/com.android.tools.build:gradle:7.4.2/g' "$MAIN_GRADLE_FILE"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
